@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package lol.roxxane.disappear_gui_overlay.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;